# Generated by Django 4.0.1 on 2022-01-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('is_online_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LiveAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=255, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.idol')),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.live')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.idol')),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('remarks', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('single', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.single')),
            ],
        ),
        migrations.AddField(
            model_name='single',
            name='sound',
            field=models.ManyToManyField(to='core.Sound'),
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mc', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('live_apparance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.liveappearance')),
                ('sound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sound')),
            ],
        ),
        migrations.AddField(
            model_name='live',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.place'),
        ),
        migrations.CreateModel(
            name='AlbumOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='idol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.idol'),
        ),
    ]
